// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	context2 "context"
)

// Injectors from wire.go:

func inject(context3 context2.Context, arg struct{}) (context, error) {
	context4, err := provide(context3)
	if err != nil {
		return context{}, err
	}
	return context4, nil
}
