// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func NewRouter() *Mux {
	homeController := &HomeController{}
	uploadController := _wireUploadControllerValue
	v := []Controller{
		homeController,
		uploadController,
	}
	mux := InitRouter(v)
	return mux
}

var (
	_wireUploadControllerValue = &UploadController{}
)
