// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectBaz() (Baz, func(), error) {
	foo, fooCleanup := provideFoo()
	bar, barCleanup, err := provideBar(foo)
	if err != nil {
		fooCleanup()
		return 0, nil, err
	}
	baz, err := provideBaz(bar)
	if err != nil {
		barCleanup()
		fooCleanup()
		return 0, nil, err
	}
	return baz, func() {
		barCleanup()
		fooCleanup()
	}, nil
}
