// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=readonly github.com/google/wire/cmd/wire gen -mod=readonly
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFoo() Foo {
	foo := provideFoo()
	return foo
}
