// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"example.com/bar"
	"golang.org/x/sync/errgroup"
)

// Injectors from wire.go:

func injectFoo(ctx context.Context) (int, error) {
	g, ctx := errgroup.WithContext(ctx)
	barBarChan := make(chan bar.Bar, 1)
	g.Go(func() error {
		barBar, err := bar.ProvideBar(ctx)
		if err != nil {
			return err
		}
		select {
		case barBarChan <- barBar:
		case <-ctx.Done():
			return ctx.Err()
		}
		return nil
	})
	int2Chan := make(chan int, 1)
	g.Go(func() error {
		var barBar bar.Bar
		select {
		case barBar = <-barBarChan:
		case <-ctx.Done():
			return ctx.Err()
		}
		int2, err := provideFoo(barBar)
		if err != nil {
			return err
		}
		select {
		case int2Chan <- int2:
		case <-ctx.Done():
			return ctx.Err()
		}
		return nil
	})
	if err := g.Wait(); err != nil {
		return 0, err
	}
	int2 := <-int2Chan
	return int2, nil
}
