// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() Baz {
	mainBazProvider := newBazProvider()
	mainFooBarProvider := newFooBarProvider()
	mainFooProvider := newFooProvider()
	foo := provideFoo(mainFooProvider)
	fooBar := provideFooBar(mainFooBarProvider, foo)
	baz := provideBaz(mainBazProvider, fooBar)
	return baz
}
