// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFooCleanup() (*FooCleanup, func()) {
	foo, fooCleanup := provideFoo()
	mainFooCleanup, mainFooCleanupCleanup := provideFooCleanup(foo)
	return mainFooCleanup, func() {
		mainFooCleanupCleanup()
		fooCleanup()
	}
}
