// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func NewRouter() *Mux {
	homeController := NewHome()
	v := []Controller{
		homeController,
	}
	mux := InitRouter(v)
	return mux
}
