// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"os"
)

// Injectors from wire.go:

func injectedFile() *os.File {
	file := os.Stdout
	return file
}
