// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFoo() int {
	int2Chan := make(chan int, 1)
	go func() {
		int2 := provideFoo()
		int2Chan <- int2
	}()
	return int2
}
