// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	bar "example.com/bar"
)

// Injectors from wire.go:

func injectFooBar() FooBar {
	foo := provideFoo()
	bar2 := bar.ProvideBar()
	fooBar := provideFooBar(foo, bar2)
	return fooBar
}
