// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package method_provider

import (
	"github.com/google/wire/tests/method_provider/animals"
)

// Injectors from wire.go:

func InitDog() *animals.Dog {
	animalsAnimals := animals.NewAnimals()
	dog := (*animals.Animals).NewDog(animalsAnimals)
	return dog
}

func InitCat() *animals.Cat {
	animalsAnimals := _wireAnimalsValue
	cat := (animals.Animals).NewCat(animalsAnimals)
	return cat
}

var (
	_wireAnimalsValue = animals.Animals{}
)
